### ISSUE TITLE
additonal resources link to wrong version

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/sql-references-join#8]
Update version of postgres linked to.

**Comment by gaand** [comment]
@jrhorn424 Should we use a version, e.g. `9.5` or should we use `current`?

**Comment by jrhorn424** [comment]
@gaand `current` please

**Comment by gaand** [comment]
@jrhorn424 I'm actually mildly opposed to using `curren`t as the version of PostgreSQL installed by brew lags `current`.  If this occurred with a major revision it would be a real pain.  But I can see the argument for easing maintenance.
